### ISSUE TITLE
用户名密码 配置provisioning添加datasources无法通讯,已经解决

### ISSUE THREAD

**Issue by gooker** [taosdata/grafanaplugin#257]
grafana:10.3
tdengine:2.6
[grafanaplugin](https://github.com/taosdata/grafanaplugin):3.4.7

```

apiVersion: 1

datasources:
- name: TDengine
  type: tdengine-datasource
  access: proxy
  orgId: 1
#   # <string> url
  url: "http://localhost:6041"
  basicAuth: true
  isDefault: true
  secureJsonData:
    url: "http://localhost:6041"
    basicAuth: "XXXXXXXXXXXXX"
  version: 1
  editable: false

```
