### ISSUE TITLE
Fail to authenticate with provisioning basicAuth in Grafana alert rule creation

### ISSUE THREAD

**Issue by davide-prade** [taosdata/grafanaplugin#280]
grafana: 11.1.4
tdengine: 3.2.3.0
grafanaplugin: 3.5.2

```yaml
apiVersion: 1
datasources:
- name: TDengine
  type: tdengine-datasource
  orgId: 1
  url: "http://taosd:6041"
  basicAuth: true
  isDefault: true
  secureJsonData:
    url: "http://taosd:6041"
    basicAuth: "cm9vdDp0YW9zZGF0YQ==" # printf root:taosdata|base64 - DO NOT WORK FOR ALERTS!
  version: 1
  editable: true
```

With this provisioned configuration dashboards works correctly, but the Grafana alert creation not (clicking on "Preview" button).

![image](https://github.com/user-attachments/assets/3a1652d3-fb3a-46cc-8cd7-c63bf6dd3890)

If I then change manually username and password from the web interface, then the alert creation works.
